from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Mainproducts)
admin.site.register(Category)
admin.site.register(Color)
admin.site.register(Rating)
admin.site.register(Size)
admin.site.register(Brand)
admin.site.register(Service)
admin.site.register(Ads)
admin.site.register(App)
admin.site.register(About)
admin.site.register(WorkStyle)
admin.site.register(Team)
admin.site.register(Location)
admin.site.register(Blog)
admin.site.register(BlogDetail)
admin.site.register(BlogComment)
admin.site.register(Faq)
admin.site.register(SubCategory)
admin.site.register(Info)
admin.site.register(Advantage)
admin.site.register(Information)
admin.site.register(Subscribers)
admin.site.register(Card)
admin.site.register(Wishlist)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Address)

